{% set name = "jack" %}
{% set version = "1.9.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jackaudio/jack2/archive/v{{ version }}.tar.gz
  sha256: 1e42b9fc4ad7db7befd414d45ab2f8a159c0b30fcd6eee452be662298766a849
  patches:
    # pick up the proper version of Python
    - waf.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('jack', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pkg-config
  host:
    - alsa-lib
    - libopus {{ libopus }}
    - eigen {{ eigen }}

test:
  commands:
    - test -f $PREFIX/lib/libjack.so
    - test -f $PREFIX/lib/pkgconfig/jack.pc
    - test -f $PREFIX/include/jack/jack.h

about:
  home: http://jackaudio.org
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: COPYING
  summary: Audio connection kit.
  summary: Audio connection kit.
  doc_url: https://github.com/jackaudio/jackaudio.github.com/wiki
  dev_url: https://github.com/jackaudio/jack2.git

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
    - ryanvolz
